const products = [
    {
        _id: "1",
        name: "Airpod Wireless Bluetooth Headphones",
        image: "/images/airpods.jpg",
        description: "descripton 1",
        brand: "Apple",
        category: "Electronics",
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: "2",
        name: "Alexa AI Embedded Speaker",
        image: "/images/alexa.jpg",
        description: "descripton 2",
        brand: "amazon",
        category: "Electronics",
        price: 298.98,
        countInStock: 14,
        rating: 3.9,
        numReviews: 43,
    },
    {
        _id: "3",
        name: "Camera",
        image: "/images/camera.jpg",
        description: "descripton 3",
        brand: "Cannon",
        category: "Electronics",
        price: 69.99,
        countInStock: 4,
        rating: 4.6,
        numReviews: 20,
    },
    {
        _id: "4",
        name: "mouse is cute",
        image: "/images/mouse.jpg",
        description: "descripton 4",
        brand: "logitech",
        category: "Electronics",
        price: 16.64,
        countInStock: 8,
        rating: 5.0,
        numReviews: 1,
    },
    {
        _id: "5",
        name: "IPhone that's it",
        image: "/images/phone.jpg",
        description: "descripton 5",
        brand: "Apple",
        category: "Electronics",
        price: 199.99,
        countInStock: 120,
        rating: 4.2,
        numReviews: 83,
    },
    {
        _id: "6",
        name: "PlayStation PS5",
        image: "/images/playstation.jpg",
        description: "descripton 6",
        brand: "IDK",
        category: "Electronics",
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
];

export default products;
